-- Insert Matthew Henry Commentary
-- Generated: 2026-04-12

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 0, 1, 0, 'commentary', 'Genesis Chapter 1 Chapter 2 Chapter 3 Chapter 4 Chapter 5 Chapter 6 Chapter 7 Chapter 8 Chapter 9 Chapter 10 Chapter 11 Chapter 12 Chapter 13 Chapter 14 Chapter 15 Chapter 16 Chapter 17 Chapter 18 Chapter 19 Chapter 20 Chapter 21 Chapter 22 Chapter 23 Chapter 24 Chapter 25 Chapter 26 Chapter 27 Chapter 28 Chapter 29 Chapter 30 Chapter 31 Chapter 32 Chapter 33 Chapter 34 Chapter 35 Chapter 36 Chapter 37 Chapter 38 Chapter 39 Chapter 40 Chapter 41 Chapter 42 Chapter 43 Chapter 44 Chapter 45 Chapter 46 Chapter 47 Chapter 48 Chapter 49 Chapter 50 AN EXPOSITION, W I T H   P R A C T I C A L   O B S E R V A T I O N S, OF THE FIRST BOOK OF MOSES, CALLED G E N E S I S.       W E have now before us the holy Bible, or book, for so bible signifies. We call it the book, by way of eminency; for it is incomparably the best book that ever was written, the book of books, shining like the sun in the firmament of learning, other valuable and useful books, like the moon and stars, borrowing their light from it. We call it the holy book, because it was written by holy men, and indited by the Holy Ghost; it is perfectly pure from all falsehood and corrupt intention; and the manifest tendency of it is to promote holiness among men.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 1, 1, 1, 'commentary', 'G E N E S I S CHAP. I.       The foundation of all religion being laid in our relation to God as our Creator, it was fit that the book of divine revelations which was intended to be the guide, support, and rule, of religion in the world, should begin, as it does, with a plain and full account of the creation of the world--in answer to that first enquiry of a good conscience, "Where is God my Maker?"', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 2, 1, 2, 'commentary', 'G E N E S I S CHAP. II.       This chapter is an appendix to the history of the creation, more particularly explaining and enlarging upon that part of the history which relates immediately to man, the favourite of this lower world. We have in it, I. The institution and sanctification of the sabbath, which was made for man, to further his holiness and comfort ( ver. 1-3 ). II. A more particular account of man''s creation, as the centre and summary of the whole work ( ver. 1-7 ).', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 3, 1, 3, 'commentary', 'G E N E S I S CHAP. III.       The story of this chapter is perhaps as sad a story (all things considered) as any we have in all the Bible. In the foregoing chapters we have had the pleasant view of the holiness and happiness of our first parents, the grace and favour of God, and the peace and beauty of the whole creation, all good, very good; but here the scene is altered. We have here an account of the sin and misery of our first parents, the wrath and curse of God against them, the peace of the creation disturbed, and its beauty stained and sullied, all bad, very bad.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 4, 1, 4, 'commentary', 'G E N E S I S CHAP. IV.       In this chapter we have both the world and the church in a family, in a little family, in Adam''s family, and a specimen given of the character and state of both in after-ages, nay, in all ages, to the end of time. As all mankind were represented in Adam, so that great distinction of mankind into saints and sinners, godly and wicked, the children of God and the children of the wicked one, was here represented in Cain and Abel.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 5, 1, 5, 'commentary', 'G E N E S I S CHAP. V.       This chapter is the only authentic history extant of the first age of the world from the creation to the flood, containing (according to the verity of the Hebrew text) 1656 years, as may easily be computed by the ages of the patriarchs, before they begat that son through whom the line went down to Noah.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 6, 1, 6, 'commentary', 'G E N E S I S CHAP. VI.       The most remarkable thing we have upon record concerning the old world is the destruction of it by the universal deluge, the account of which commences in this chapter, wherein we have, I. The abounding iniquity of that wicked world, ver. 1-5 , and ver. 11, 12 . II. The righteous God''s just resentment of that abounding iniquity, and his holy resolution to punish it, ver. 6, 7 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 7, 1, 7, 'commentary', 'G E N E S I S CHAP. VII.       In this chapter we have the performance of what was foretold in the foregoing chapter, both concerning the destruction of the old world and the salvation of Noah; for we may be sure that no word of God shall fall to the ground. There we left Noah busy about his ark, and full of care to get it finished in time, while the rest of his neighbours were laughing at him for his pains.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 8, 1, 8, 'commentary', 'G E N E S I S CHAP. VIII.       In the close of the foregoing chapter we left the world in ruins and the church in straits; but in this chapter we have the repair of the one and the enlargement of the other. Now the scene alters, and another face of things begins to be presented to us, and the brighter side of that cloud which there appeared so black and dark; for, though God contend long, he will not contend for ever.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 9, 1, 9, 'commentary', 'G E N E S I S CHAP. IX.       Both the world and the church were now again reduced to a family, the family of Noah, of the affairs of which this chapter gives us an account, of which we are the more concerned to take cognizance because from this family we are all descendants. Here is, I. The covenant of providence settled with Noah and his sons, ver. 1-11.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 10, 1, 10, 'commentary', 'G E N E S I S CHAP. X.       This chapter shows more particularly what was said in general ( ch. ix. 19 ), concerning the three sons of Noah, that "of them was the whole earth overspread;" and the fruit of that blessing ( ch. ix. 1, 7 ), "replenish the earth." Is is the only certain account extant of the origin of nations.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 11, 1, 11, 'commentary', 'G E N E S I S CHAP. XI.       The old distinction between the sons of God and the sons of men (professors and profane) survived the flood, and now appeared again, when men began to multiply: according to this distinction we have, in this chapter, I. The dispersion of the sons of men at Babel ( ver. 1-9 ).', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 12, 1, 12, 'commentary', 'G E N E S I S CHAP. XII.       The pedigree and family of Abram we had an account of in the foregoing chapter; here the Holy Ghost enters upon his story, and henceforward Abram and his seed are almost the only subject of the sacred history. In this chapter we have, I. God''s call of Abram to the land of Canaan, ver. 1-3 . II. Abram''s obedience to this call, ver. 4, 5 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 13, 1, 13, 'commentary', 'G E N E S I S CHAP. XIII.       In this chapter we have a further account concerning Abram. I. In general, of his condition and behaviour in the land of promise, which was now the land of his pilgrimage. 1. His removes, ver. 1, 3, 4, 18 . 2. His riches, ver. 2 . 3. His devotion, ver. 4, 18 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 14, 1, 14, 'commentary', 'G E N E S I S CHAP. XIV.       We have four things in the story of this chapter. I. A war with the king of Sodom and his allies, ver. 1-11 . II. The captivity of Lot in that war, ver. 12 . III. Abram''s rescue of Lot from that captivity, with the victory he obtained over the conquerors, ver. 13-16 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 15, 1, 15, 'commentary', 'G E N E S I S CHAP. XV.       In this chapter we have a solemn treaty between God and Abram concerning a covenant that was to be established between them. In the former chapter we had Abram in the field with kings; here we find him in the mount with God; and, though there he looked great, yet, methinks, here he looks much greater.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 16, 1, 16, 'commentary', 'G E N E S I S CHAP. XVI.       Hagar is the person mostly concerned in the story of this chapter, an obscure Egyptian woman, whose name and story we never should have heard of if Providence had not brought her into the family of Abram. Concerning her, we have four things in this chapter:-- I. Her marriage to Abram her master, ver. 1-3 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 17, 1, 17, 'commentary', 'G E N E S I S CHAP. XVII.       This chapter contains articles of agreement covenanted and concluded upon between the great Jehovah, the Father of mercies, on the one part, and pious Abram, the father of the faithful, on the other part. Abram is therefore called "the friend of God," not only because he was the man of his counsel, but because he was the man of his covenant.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 18, 1, 18, 'commentary', 'G E N E S I S CHAP. XVIII.       We have an account in this chapter of another interview between God and Abraham, probably within a few days after the former, as the reward of his cheerful obedience to the law of circumcision. Here is, I. The kind visit which God made him, and the kind entertainment which he gave to that visit, ver. 1-8 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 19, 1, 19, 'commentary', 'G E N E S I S CHAP. XIX.       The contents of this chapter we have, 2 Pet. ii. 6-8 , where we find that "God, turning the cities of Sodom and Gomorrah into ashes, condemned them with an overthrow, and delivered just Lot." It is the history of Sodom''s ruin, and Lot''s rescue from that ruin.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 20, 1, 20, 'commentary', 'G E N E S I S CHAP. XX.       We are here returning to the story of Abraham; yet that part of it which is here recorded is not to his honour. The fairest marbles have their flaws, and, while there are spots in the sun, we must not expect any thing spotless under it. The scripture, it should be remarked, is impartial in relating the blemishes even of its most celebrated characters.', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 21, 1, 21, 'commentary', 'G E N E S I S CHAP. XXI.       In this chapter we have, I. Isaac, the child of promise born into Abraham''s family, ver. 1-8 . II. Ishmael, the son of the bondwoman, cast out of it, ver. 9-21 . III. Abraham''s league with his neighbour Abimelech, ver. 22-32 . IV. His devotion to his God, ver. 33 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 22, 1, 22, 'commentary', 'G E N E S I S CHAP. XXII.       We have here the famous story of Abraham''s offering up his son Isaac, that is, his offering to offer him, which is justly looked upon as one of the wonders of the church. Here is, I. The strange command which God gave to Abraham concerning it, ver. 1, 2 . II. Abraham''s strange obedience to this command, ver. 3-10 .', 'matthew_henry');

INSERT INTO study_notes (book_id, chapter, verse_start, verse_end, note_type, content, source) VALUES ('gn', 23, 1, 23, 'commentary', 'G E N E S I S CHAP. XXIII.       Here is, I. Abraham a mourner for the death of Sarah, ver. 1, 2 . II. Abraham a purchaser of a burying-place for Sarah. 1. The purchase humbly proposed by Abraham, ver. 3, 4 . 2. Fairly treated of, and agreed to, with a great deal of mutual civility and respect, ver. 5-16 .', 'matthew_henry');