-- Add Medieval Theologians Comments
-- Tomás de Aquino, Bernardo de Claraval, Anselmo de Cantuária, Boaventura, Gregório de Nissa, Máximo o Confessor, João Damasceno
-- This migration adds comprehensive comments from medieval theologians

BEGIN;

-- Tomás de Aquino (Thomism) - Pentateuco
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-aquinas-gn-1-1', 'gn', 1, 1, NULL, 'Tomismo', ' Tomás de Aquino commenta que o texto de Gênesis 1:1 estabelece o fundamento de toda a criação ex nihilo. A doutrina da criação distingue-se da制造业 (fabricação) porque Deus não usa material preexistente. Este princípio é fundamental para a teologia natural e as Cinco Vias.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-gn-1-26', 'gn', 1, 26, NULL, 'Tomismo', 'O Doctor Angelicus ensina que o homem foi criado à imagem e semelhança de Deus (imago Dei), o que significa a participação na razão e na vontade divina. A alma humana é criada individualmente por Deus, sendo imortal e.dotada de livre-arbítrio.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-ex-3-14', 'ex', 3, 14, NULL, 'Tomismo', 'Na questão do nome divino "Eu Sou o que Sou", Tomás de Aquino explica que este nome expressa a natureza divina como Ser subsistente e necessário. É o nome mais próprio de Deus, diferenciando-O de todas as criaturas que têm um ser participado.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-lv-19-18', 'lv', 19, 18, NULL, 'Tomismo', 'O amor ao próximo como a si mesmo é o第二个mandamento maior, segundo Tomás. Este preceito é a expressão da lei natural inscrita no coração humano. A caridade (amor de Deus) e a justiça (amor ao próximo) são as duas dimensões fundamentais da virtude.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-dt-6-4', 'dt', 6, 4, NULL, 'Tomismo', 'O Shema Israel representa o primeiro princípio da lei natural. Tomás de Aquino ensina que as verdades fundamentais sobre Deus são evidentes pela razão natural. A unidade de Deus é demonstrável filosoficamente, mas revelada historicamente ao povo de Israel.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-sl-23', 'sl', 23, NULL, NULL, 'Tomismo', 'O salmista descreve Deus como Pastor que guia as almas pelos vales escuros. Tomás commenta que a providência divina não elimina o livre-arbítrio humano, mas o ordena. A graça não destrói a natureza, mas a perfecciona.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-mt-5-17', 'mt', 5, 17, NULL, 'Tomismo', 'Cristo não veio abolir a Lei, mas cumpli-la. Tomás de Aquino explica que a Lei antiga era um pedagogo que preparava para Cristo. A lei nova (Evangelho) é a lei da liberdade interior, escrita no coração pelo Espírito Santo.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-rm-8-26', 'rm', 8, 26, NULL, 'Tomismo', 'O Espírito intercede por nós com gemidos inexprimíveis. Tomás ensina que a graça sanctificante eleva a natureza humana sem destruí-la. A oração é a expressão do desejo natural do homem por Deus, Perfection suprema.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-1co-13', '1co', 13, NULL, NULL, 'Tomismo', 'O hino à caridade de Paulo é comentado por Tomás como a più excelente das virtudes teologais. A caridade é o vínculo de perfectio que une o homem a Deus. Sem ela, todas as demais obras são como sonido que não toca.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW()),
('medieval-aquinas-ef-1-3', 'ef', 1, 3, NULL, 'Tomismo', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou em Cristo. Tomás commenta a doutrina da eleição: Deus, na Sua providência, escolhe一些人 para a glória. A prédestinação é um mistério que excede a razão mas não a contradiz.', 'Tomás de Aquino', 'commentary', '#1E40AF', NOW());

-- Bernardo de Claraval (Misticismo)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-bernard-ct-1-2', 'ct', 1, 2, NULL, 'Misticismo', 'Bernardo de Claraval, o Doctor Mellifluus, interpreta o Cantar dos Cantares como a narrativa da alma que busca a união mística com Cristo. O beijo da boca representa a união das vontades, o nível mais alto da vida espiritual.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-sl-51', 'sl', 51, NULL, NULL, 'Misticismo', 'O penitente David suplica "Cria em mim um coração limpo". Bernardo commenta que a pureza de coração é o pré-requisito para ver a Deus. Esta purificação é obra da graça que actua através dos sacramentos e da mortificação.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-jn-15-1', 'jo', 15, 1, NULL, 'Misticismo', 'Eu sou a videira verdadeira. Bernardo ensina que a videira symboliza a humanidade de Cristo, e os ramos são os fiéis. A videira só pode ser cultivada pelo Pai (purgação), nutrida pelo Filho (iluminação) e vivificada pelo Espírito (união).', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-lc-1-38', 'lc', 1, 38, NULL, 'Misticismo', 'A Anunciação é o momento da colaboração entre a graça divina e a liberdade humana. Maria não foi simplesmente passiva, mas consentiu ativamente. Bernardo vê na disponibilidade de Maria o modelo de toda cooperação com a graça.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-1pe-2-4', '1pe', 2, 4, NULL, 'Misticismo', 'Vindo a ele, pedra viva. Bernardo commenta que Cristo é a pedra angular onde o fiel deve edificar sua vida espiritual. A mortificação (pedra de rejeição) torna-se fundação de glória para quem aceita Cristo com fé.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-hb-12-1', 'hb', 12, 1, NULL, 'Misticismo', 'Corramos com perseverança a corrida que nos é proposta. O Doctor Seraphicus ensina que a vida espiritual é uma maratona, não uma corrida de curta distância. A perseverança é o critério final da verdadeira piedade.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-jo-17-21', 'jo', 17, 21, NULL, 'Misticismo', 'Bernardo interpreta a oração de Cristo pela unidade como fundamento da vida monástica. A unidade entre os fiéis é imagem da единияtrina (unidade) trinitária. A caridade é o vínculo que torna os muitos um só.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW()),
('medieval-bernard-ap-21-2', 'ap', 21, 2, NULL, 'Misticismo', 'A Nova Jerusalén é a Igreja purified e glorificada. Bernardo, ao comentar o Apocalipse, ensina que a visão beatífica é o fim último do homem. Aglória celestial consiste na visão face a face de Deus,GO-SP-2021-001.', 'Bernardo de Claraval', 'commentary', '#7C3AED', NOW());

-- Anselmo de Cantuária (Escolástica)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-anselm-sl-14-1', 'sl', 14, 1, NULL, 'Escolástica', 'Anselmo, o Pai da Escolástica, ensina que a prova da existência de Deus pela fé (fides quaerens intellectum) é o método teológico fundamental. O argumento ontológico parte da ideia de Deus como o maior de todos os seres concebíveis.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-gn-28-10', 'gn', 28, 10, NULL, 'Escolástica', 'Jacó sonhou com a escada que alcançava o céu. Anselmo interpreta a escada como símbolo da escala da perfeição. O homem deve subir degrau por degrau: da fé à esperança, da esperança à caridade.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-hb-11-1', 'hb', 11, 1, NULL, 'Escolástica', 'A fé é o fundamento das coisas que se esperam, e prova das que não se veem. Anselmo desenvolve a doutrina de que a razão deve servir à fé, mas a fé também eleva a razão. Não há conflito entre filosofia e teologia.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-jo-14-6', 'jo', 14, 6, NULL, 'Eu sou o caminho, a verdade e a vida. Anselmo commenta que Cristo é o único mediador entre Deus e os homens. A是人类não pode chegar a Deus por seus próprios méritos, mas através da humanidade assumida por Cristo.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-rm-3-23', 'rm', 3, 23, NULL, 'Todos pecaram e estão privados da glória de Deus. Anselmo explica que o pecado original não é simplesmente imitável, mas uma condição herdada. A solução não pode ser meramente humana, pois a ofensa é infinita.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-2sm-7-12', '2sm', 7, 12, NULL, 'Estabelecerei o trono de teu reino para sempre. Anselmo vê nesta promessa messiânica o fundamento da esperança cristã. O Reino de Cristo não é deste mundo, mas transcende todos os reinos terrenos.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-mt-5-8', 'mt', 5, 8, NULL, 'Bem-aventurados os puros de coração, pois verão a Deus. O Pai da Escolástica ensina que a pure heart é resultado da graça preveniente e da cooperação humana. A visão beatífica é o prêmio da vida virtuosa.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW()),
('medieval-anselm-cl-1-15', 'cl', 1, 15, NULL, 'Ele é a imagem do Deus invisível. Anselmo desenvolve a cristologia como perfeito homo,perfectus Deus. A humanidade de Cristo não dilui a divindade, mas a revela de forma visível ao homem.', 'Anselmo de Cantuária', 'commentary', '#047857', NOW());

-- Boaventura (Escola Franciscana)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-bonaventure-sl-104-1', 'sl', 104, 1, NULL, 'Franciscana', 'Boaventura, o Doctor Seraphicus, commenta que a criação é um livro onde Deus Se revela. A natureza é sagrada porque carrega a marca do Criador. O Franciscanismo vê em cada criatura um reflexo da bondade divina.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-lc-1-46', 'lc', 1, 46, NULL, 'Franciscana', 'A oração de Maria (Magnificat) é o modelo da humildade franciscana. Boaventura ensina que a verdadeira sabedoria está em reconhecer a própria nada diante de Deus. O pobre de espírito é aquele que não se apega a nada.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-mt-25-40', 'mt', 25, 40, NULL, 'Franciscana', 'O juízo final baseia-se no amor mostrado aos pobres. Boaventura interpreta literalmente a opção pelos pobres como critério de salvação. A caridade concretiza-se no serviço aos necessitados, especialmente os menores.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-jo-20-22', 'jo', 20, 22, NULL, 'Recebei o Espírito Santo. O Doctor Seraphicus ensina que o Espírito Santo é oDomador que produz os frutos da caridade. Os sete dons do Espírito são necessários para a vida espiritual perfeita.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-1co-12-4', '1co', 12, 4, NULL, 'Há diversidade de dons, mas o mesmo Espírito. Boaventura commenta a complementaridade dos carismas na Igreja. Cada membro tem um papel único no Corpo de Cristo, guiado pelo mesmo Espírito.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-sl-23-4', 'sl', 23, 4, NULL, 'Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum. Boaventura, na tradição franciscana, vê a cruz como caminho de luz. O sofrimento, Offered a Deus, torna-se fonte de graça.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-rm-8-18', 'rm', 8, 18, NULL, 'Penso que os sofrimentos do tempo presente não merecem comparação com a glória que há de revelar-se em nós. O Doctor Seraphicus ensina que a glória futura excede incomparavelmente os sofrimentos presente.', 'Boaventura', 'commentary', '#C026D3', NOW()),
('medieval-bonaventure-ef-3-18', 'ef', 3, 18, NULL, 'Possais compreender, com todos os santos, qual é a largura, e o comprimento, e a altura, e a profundidade. Boaventura desenvolve a teologia mística das dimensões do amor de Cristo que excede todo conhecimento.', 'Boaventura', 'commentary', '#C026D3', NOW());

-- Gregório de Nissa (Padre Capadócio)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-gregory-nissa-gn-1-1', 'gn', 1, 1, NULL, 'Padre Capadócio', 'Gregório de Nissa, Doctor Christianorum, commenta que a criação ex nihilo implica que nada existe fora de Deus a não ser o que Deus criou. O null (nada) não é um princípio eterno, mas simplesmente a ausência de ser criado.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-2co-3-18', '2co', 3, 18, NULL, 'Padre Capadócio', 'Todos nós, com rosto descoberto, contemplando como num espelho a glória do Senhor, somos transformados na mesma imagem. Gregório desenvolve a doutrina da theosis (deificação) - o homem pode participar da natureza divina.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-rm-8-29', 'rm', 8, 29, NULL, 'Padre Capadócio', 'A prédestinação não anula o livre-arbítrio. Gregório de Nissa ensina que Deus antevê mas não determina forçosamente. A graça é offered a todos, mas a colaboração humana é essential para a salvação.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-mt-5-48', 'mt', 5, 48, NULL, 'Padre Capadócio', 'Sede perfeitos como vosso Pai celestial é perfeito. Gregório interpreta a perfeição como um processo contínuo de divinização. O caminho é longo: da purificação à iluminação, e finalmente à união.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-jo-17-3', 'jo', 17, 3, NULL, 'Esta é a vida eterna: que Te conheçam, o único Deus verdadeiro, e a Jesus Cristo. O Doctor Christianorum ensina que o conhecimento de Deus é progressivo nesta vida, mas perfeito na vida futura. A teologia negativa é o método de aproximação ao Inefável.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-hb-4-12', 'hb', 4, 12, NULL, 'A palavra de Deus é viva e eficaz, e mais cortante que qualquer espada de dois gumes. Gregório desenvolve a doutrina do_logos como oVerbo que penetra as profundezas da alma. A Escritura tem múltiplos sentidos: literal, moral, alegórico, anagógico.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-ef-4-4', 'ef', 4, 4, NULL, 'Um só corpo, um só Espírito. Gregório de Nissa ensina a doutrina da Igreja como Corpo Místico de Cristo. A unidade não é uniformidade, mas diversidade harmônica. O Espírito Santo é o princípio de unidade.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW()),
('medieval-gregory-nissa-sl-139-1', 'sl', 139, 1, NULL, 'Senhor, Tu me sondas e me conheces. Gregório commenta a onisciência divina como conhecimento não temporal, mas eterno. Deus não conhece o futuro como algo exterior, mas o apresenta em Sua eternidade.', 'Gregório de Nissa', 'commentary', '#0891B2', NOW());

-- Máximo o Confessor (Misticismo Bizantino)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-maximus-cl-2-9', 'cl', 2, 9, NULL, 'Misticismo Bizantino', 'Maximo o Confessor, Doctor Maximus, ensina que em Cristo habita corporalmente toda a plenitude da divindade. A união hipostática é o modelo de toda união entre o divino e o humano na vida espiritual.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-rm-12-1', 'rm', 12, 1, NULL, 'Ofereçam os vossos corpos como sacrifício vivo. O Confessor desenvolve a teologia da transfiguração: o corpo não é mau, mas pode ser divinizado. A ascese não destrói o corpo, mas o eleva.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-jo-14-23', 'jo', 14, 23, NULL, 'Se alguém Me ama, guardará a Minha palavra. Maximo ensina que a união mística é a participação na vida trinitária. O amor de Cristo não é merely emocional, mas ontológico - uma comunhão de natureza.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-1jo-4-8', '1jo', 4, 8, NULL, 'Deus é amor. O Doctor Maximus interpreta a definição joanina como a essência divina. O amor não é atributo entre outros, mas a própria natureza de Deus. O homem é criado para participar desse amor.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-ef-3-16', 'ef', 3, 16, NULL, 'Que segundo a riqueza da Sua glória vos conceda serdes fortificados com o Seu poder no homem interior. Maximo desenvolve a doutrina da energia divina: Deus comunica-Se sem Se misturar às criaturas.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-mc-12-30', 'mc', 12, 30, NULL, 'Amarás o Senhor teu Deus de todo o teu coração, de toda a tua alma, de todo o teu entendimento e de toda a tua força. O Confessor comenta os quatro movimentos da alma: inferiores (coração), superiores (alma), razão (entendimento), e força (vontade).', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-2pe-1-4', '2pe', 1, 4, NULL, 'Para que vos tornéis participantes da natureza divina. Maximo o Confessor é o principalizador da doutrina da theosis. O homem não se torna Deus literalmente, mas participa da natureza divina por graça.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW()),
('medieval-maximus-ap-21-10', 'ap', 21, 10, NULL, 'A Cidade Santa, a nova Jerusalén, descia do céu, da parte de Deus. O Doctor Maximus interpreta a visão apocalíptica como a Igreja glorificada. A unidade da Igreja é prefiguração da unidade escatológica.', 'Maximo o Confessor', 'commentary', '#BE185D', NOW());

-- João Damasceno (Teologia Sistemática)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at)
VALUES 
('medieval-john-damascene-gn-1-27', 'gn', 1, 27, NULL, 'Teologia Oriental', 'João Damasceno, Doctor Orientalis, ensina que o homem foi criado à imagem de Deus, o que significa a capacidade de participar da natureza divina. A razão distingue o homem dos animais, e a livre vontade o distingue das coisas inanimadas.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-ex-20-4', 'ex', 20, 4, NULL, 'Teologia Oriental', 'Não farás para ti imagem talhada. O Damasceno explica que a proibição visa os ídolos, não as imagens legítimas. Os ícones são janelas para o céu, não objetos de adoração, mas de veneração.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-sl-2-7', 'sl', 2, 7, NULL, 'Teologia Oriental', 'Hoje vos gerei. João Damasceno explica a eternidade do Filho em relação à Sua missão histórica. O Logos é gerado eternamente, não temporalmente. A Encarnação é a manifestação de uma verdade eterna.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-jo-1-1', 'jo', 1, 1, NULL, 'Teologia Oriental', 'No princípio era o Verbo. O Doctor Orientalis comenta a doutrina do Logos como razão divina que penetra toda a criação. A teologia oriental enfatiza a sabedoria (sophia) como atributo central de Deus.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-mt-28-19', 'mt', 28, 19, NULL, 'Teologia Oriental', 'Batizando-os em nome do Pai, e do Filho, e do Espírito Santo. A Trindade é um só Deus em três pessoas. João Damasceno sistematiza a teologia oriental: o Pai é a origem, o Filho é o Verbo, o Espírito é o Espírito.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-1tm-2-5', '1tm', 2, 5, NULL, 'Teologia Oriental', 'Há um só Deus, e um só Mediador entre Deus e os homens: Jesus Cristo. O Damasceno ensina que Cristo é o único mediator porque é simultaneamente Deus e homem. A mediação não é exercício, mas naturaleza.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-hb-9-14', 'hb', 9, 14, NULL, 'Quanto mais o sangue de Cristo, que Se offeriu a Si mesmo como sacrifício sem defeito através do Espírito eterno, purificará a nossa consciência. O Doctor Orientalis desenvolve a doutrina do sacrifício único e perfeito.', 'João Damasceno', 'commentary', '#6366F1', NOW()),
('medieval-john-damascene-cl-1-19', 'cl', 1, 19, NULL, 'Porque nEle corporizou-se toda a plenitude. João Damasceno ensina a totalidade da divindade em Cristo. Os dois casos (divino e humano) subsistem em uma única hypostasis. Esta é a doutrina calcedoniana explicada.', 'João Damasceno', 'commentary', '#6366F1', NOW());

-- Add new note_type for user annotations (if table doesn't exist yet)
-- This will fail gracefully if the table already exists or has the column
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'study_notes' AND column_name = 'note_type' AND column_default = '''commentary'''::text) THEN
    -- Column already exists, nothing to do
  END IF;
EXCEPTION WHEN duplicate_column THEN
  -- Ignore
END $$;

COMMIT;